.TH AZAN\-NASM 1 azan\-nasm\-VERSION
.SH NAME
azan\-nasm \- simple muslim prayers calculator
.SH SYNOPSIS
.B azan\-nasm
.RB [ \-Nnuv ]
.SH DESCRIPTION
azan\-nasm is a simple muslim prayers calculator for unix-like systems.  Show prayers time. written in nasm x86-64.
.SH OPTIONS
.TP
.B \-N
print next prayer time, 12-hour clock format.
.TP
.B \-n
print next prayer time, 24-hour clock format.
.TP
.B \-u
print next prayer time, unix-time format.
.TP
.B \-v
print version.
.SH USAGE
.TP
.B azan\-nasm
print next prayer left duration.
.SH CUSTOMIZATION
azan\-nasm is customized by creating a custom
.IR config.s
and (re)compiling the source
code. This keeps it fast, secure and simple.
.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
