.TH AZAN 1 azan\-VERSION
.SH NAME
azan \- simple muslim prayers calculator
.SH SYNOPSIS
.B azan
.SH DESCRIPTION
azan is a simple muslim prayers calculator for unix-like systems.  Show prayers time.
.SH USAGE
.TP
.B azan
print next prayer left duration.
.SH AUTHORS
See the LICENSE file for the authors.
.SH LICENSE
See the LICENSE file for the terms of redistribution.
